version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate
      - persist_to_workspace:
          root: public
          paths:
            - '*'
  deploy:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - 'e9:bf:9d:84:5b:8a:7a:d6:b3:2a:3d:b2:ba:31:44:2c'
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "The Mark"
            git config --global user.email "sunduo3195@qq.com"
            sh build.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: blog
